### ISSUE TITLE
what's the versio of the open3d?

### ISSUE THREAD

**Issue by LYFAthena** [simeseg/icp#2]
thanks for your code about icp, when I try to run the code in my pc that installed open3d version as 0.10.0, I found an error as

Traceback (most recent call last):
  File "/Users/mac/Downloads/icp-main/run.py", line 26, in <module>
    icp = icp_LM(4, 1, 20, "plane", True, model, scene)
  File "/Users/mac/Downloads/icp-main/icp_LM.py", line 30, in __init__
    self.model.orient_normals_consistent_tangent_plane(k=15)
AttributeError: 'open3d.open3d_pybind.geometry.PointCloud' object has no attribute 'orient_normals_consistent_tangent_plane'

so I consider maybe the error is caused by the open3d version 
or do you have any idea to this error?
many thans for your reply : )

**Comment by PolarisXQ** [comment]
i triedopen3d 0.16.0 and it worked :)
